blog/blog/apps/post/urls.py
from django.urls import path
import apps.post.views as views

app_name = "post"

urlpatterns = [
    path('posts/', views.PostListView.as_view(), name="post_list"),
    path('posts/create/', views.PostCreateView.as_view(), name="post_create"),
    path('posts/<slug:slug>/', views.PostDetailView.as_view(), name="post_detail"),
    path('posts/<slug:slug>/update/', views.PostUpdateView.as_view(), name="post_update"),
    path('posts/<slug:slug>/delete/', views.PostDeleteView.as_view(), name="post_delete"),
    path('posts/<slug:slug>/comments/create/', views.CommentCreateView.as_view(), name="comment_create"),
    path('comments/<uuid:pk>/update/', views.CommentUpdateView.as_view(), name="comment_update"),
    path('comments/<uuid:pk>/delete/', views.CommentDeleteView.as_view(), name="comment_delete"),
]

blog/blog/apps/user/urls.py
from django.urls import path
import apps.user.views as views

app_name = "user"

urlpatterns = [
    path('users/profile/', views.UserProfileView.as_view(), name="user_profile"),
    path('auth/register/', views.RegisterView.as_view(), name="auth_register"),
    path('auth/login/', views.LoginView.as_view(), name="auth_login"),
    path('auth/logout/', views.LogoutView.as_view(), name="auth_logout"),
]

blog/blog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from blog.views import IndexView, not_found_view, internal_error_view, forbidden_view

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', IndexView.as_view(), name="home"),
    path('', include('apps.post.urls')),
    path('', include('apps.user.urls')),
]

handler404 = not_found_view
handler500 = internal_error_view
handler403 = forbidden_view

if settings.DEBUG:
    from django.conf.urls.static import static
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

blog/blog/apps/post/models.py
from django.db import models
from django.utils import timezone
from django.conf import settings
from django.utils.text import slugify
import uuid
import os


class Post(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    title = models.CharField(max_length=200)
    slug = models.SlugField(unique=True, max_length=200, blank=True)
    content = models.TextField(max_length=10000)
    author = models.ForeignKey(
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    creation_date = models.DateTimeField(default=timezone.now)
    modification_date = models.DateTimeField(auto_now=True)
    allow_comments = models.BooleanField(default=True)

    def __str__(self):
        return self.title

    @property
    def amount_comments(self):
        return self.comments.count()

    @property
    def amount_images(self):
        return self.images.count()

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = self.generate_unique_slug()
        super().save(*args, **kwargs)

    def generate_unique_slug(self):
        # tenemos este titulo para el post
        # tenemos-este-titulo-para-el-post

        # tenemos-este-titulo-para-el-post-1
        # tenemos-este-titulo-para-el-post-2
        # tenemos-este-titulo-para-el-post-3
        slug = slugify(self.title)
        unique_slug = slug
        num = 1

        while Post.objects.filter(slug=unique_slug).exists():
            unique_slug = f'{slug}-{num}'
            num += 1

        return unique_slug


def get_image_filename(instance, filename):
    # imagen3121212      .png            imagen3121212.png
    base_filename, file_extension = os.path.splitext(filename)
    images_count = instance.post.images.count()
    new_filename = f"post_{instance.post.id}_cover_{images_count + 1 }{file_extension}"
    # post_asdasdas123asda123sadasde12_cover_1.jpg
    return os.path.join('post/cover/', new_filename)

class PostImage(models.Model):
    post = models.ForeignKey(
        Post, on_delete=models.CASCADE, related_name='images')
    image = models.ImageField(
        upload_to=get_image_filename, default=settings.DEFAULT_POST_IMAGE)
    active = models.BooleanField(default=True)
    creation_date = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return f"PostImage {self.id}"


class Comment(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    content = models.TextField(max_length=500)
    creation_date = models.DateTimeField(auto_now_add=True)
    author = models.ForeignKey(settings.AUTH_USER_MODEL,
                               on_delete=models.CASCADE)
    post = models.ForeignKey(
        Post, on_delete=models.CASCADE, related_name='comments')

    def __str__(self):
        return self.content

blog/blog/apps/post/forms.py
from django import forms
from apps.post.models import Post, PostImage, Comment

class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('title', 'content', 'allow_comments')


class NewPostForm(PostForm):
    image = forms.ImageField(required=False)

    def save(self, commit=True):
        post = super().save(commit=False)
        image = self.cleaned_data['image']

        if commit:
            post.save()
            if image:
                PostImage.objects.create(post=post, image=image)
        return post


class UpdatePostForm(PostForm):
    image = forms.ImageField(required=False)

    def __init__(self, *args, **kwargs):
        self.active_images = kwargs.pop('active_images', None)
        super(UpdatePostForm, self).__init__(*args, **kwargs)

        if self.active_images:
            for image in self.active_images:
                # keep_image_1, keep_image_2...
                field_name = f"keep_image_{image.id}"
                self.fields[field_name] = forms.BooleanField(
                    required=False, initial=True, label=f"Mantener {image}"
                )

    def save(self, commit=True):
        post = super().save(commit=False)
        image = self.cleaned_data['image']

        if commit:
            post.save()

            if image:
                PostImage.objects.create(post=post, image=image)
            
            if self.active_images:
                for image in self.active_images:
                    if not self.cleaned_data.get(f"keep_image_{image.id}", True):
                        image.delete()
        return post
            

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['content']

        labels = {
            'content': 'Comentario'
        }

        widgets = {
            'content': forms.Textarea(attrs={'rows': 3, 'placeholder': 'Escribe tu comentario...', 'class': 'p-2'})
        }


class PostFilterForm(forms.Form):
    search_query = forms.CharField(
        required=False,
        widget=forms.TextInput(attrs={'placeholder': 'Buscar...', 'class': 'w-full p-2'})
    )
    order_by = forms.ChoiceField(
        required=False,
        choices=(
            ('-creation_date', 'Más recientes'),
            ('creation_date', 'Más antiguos'),
            ('-comments_count', 'Más comentados'),
        ),
        widget=forms.Select(attrs={'class': 'w-full p-2'})
    )

blog/blog/apps/post/views.py
from django.views.generic import ListView, DetailView, CreateView, DeleteView, UpdateView
from apps.post.models import Post, PostImage, Comment
from apps.post.forms import NewPostForm, UpdatePostForm, CommentForm, PostFilterForm
from django.urls import reverse, reverse_lazy
from django.conf import settings
from django.shortcuts import get_object_or_404
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.db.models import Count


class PostListView(ListView):
    model = Post
    template_name = 'post/post_list.html'
    context_object_name = 'posts'
    paginate_by = 1

    def get_queryset(self):
        queryset = Post.objects.all().annotate(comments_count=Count('comments'))
        search_query = self.request.GET.get('search_query', '')
        order_by = self.request.GET.get('order_by', '-creation_date')

        if search_query:
            queryset = queryset.filter(title__icontains=search_query) | queryset.filter(author__username__icontains=search_query)

        return queryset.order_by(order_by)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['filter_form'] = PostFilterForm(self.request.GET)

        if context.get('is_paginated', False):
            query_params = self.request.GET.copy()
            query_params.pop('page', None)

            # Paginacion
            pagination = {}
            page_obj = context['page_obj']
            paginator = context['paginator']

            if page_obj.number > 1:
                pagination['first_page'] = f'?{query_params.urlencode()}&page={paginator.page_range[0]}'

            if page_obj.has_previous():
                pagination['previous_page'] = f'?{query_params.urlencode()}&page={page_obj.number - 1}'

            if page_obj.has_next():
                pagination['next_page'] = f'?{query_params.urlencode()}&page={page_obj.number + 1}'

            if page_obj.number < paginator.num_pages:
                pagination['last_page'] = f'?{query_params.urlencode()}&page={paginator.num_pages}'
            
            context['pagination'] = pagination

        return context


class PostCreateView(CreateView):
    model = Post
    form_class = NewPostForm
    template_name = 'post/post_create.html'

    def form_valid(self, form):
        form.instance.author = self.request.user
        post = form.save()

        images = self.request.FILES.getlist('images')

        if images:
            for image in images:
                PostImage.objects.create(post=post, image=image)
        else:
            PostImage.objects.create(
                post=post, image=settings.DEFAULT_POST_IMAGE)

        return super().form_valid(form)

    def get_success_url(self):
        return reverse('post:post_detail', kwargs={'slug': self.object.slug})


class PostDetailView(DetailView):
    model = Post
    template_name = 'post/post_detail.html'
    context_object_name = 'post'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        active_images = self.object.images.filter(active=True)

        context['active_images'] = active_images
        context['add_comment_form'] = CommentForm()

        # Editar comentario
        edit_comment_id = self.request.GET.get('edit_comment')
        if edit_comment_id:
            comment = get_object_or_404(Comment, id=edit_comment_id)

            if comment.author == self.request.user:
                context['editing_comment_id'] = comment.id
                context['edit_comment_form'] = CommentForm(instance=comment)
            else:
                context['editing_comment_id'] = None
                context['edit_comment_form'] = None

        # Eliminar comentario
        delete_comment_id = self.request.GET.get('delete_comment')
        if delete_comment_id:
            comment = get_object_or_404(Comment, id=delete_comment_id)

            if (
                # Es autor del comentario
                comment.author == self.request.user or
                # Es autor del post, pero el comentario no es de un admin o un superuser
                (comment.post.author == self.request.user and not comment.author.is_admin and not comment.author.is_superuser) or
                self.request.user.is_superuser or  # Es Superuser
                self.request.user.groups.filter(
                    name="Admins").exists()  # Es Admin
            ):
                context['deleting_comment_id'] = comment.id
            else:
                context['deleting_comment_id'] = None

        return context


class PostUpdateView(UpdateView):
    model = Post
    form_class = UpdatePostForm
    template_name = 'post/post_update.html'

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs['active_images'] = self.get_object().images.filter(active=True)
        return kwargs

    def form_valid(self, form):
        post = form.save(commit=False)
        active_images = form.active_images
        keep_any_image_active = False

        # Manetener images
        if active_images:
            for image in active_images:
                field_name = f"keep_image_{image.id}"

                if not form.cleaned_data.get(field_name, True):
                    image.active = False
                    image.save()
                else:
                    keep_any_image_active = True

        # Agregar nuevas images
        images = self.request.FILES.getlist('images')
        if images:
            for image in images:
                PostImage.objects.create(post=post, image=image)

        # No agrega ni mantiene images
        if not keep_any_image_active and not images:
            PostImage.objects.create(
                post=post, image=settings.DEFAULT_POST_IMAGE)

        post.save()
        return super().form_valid(form)

    def get_success_url(self):
        return reverse_lazy('post:post_detail', kwargs={'slug': self.object.slug})


class PostDeleteView(DeleteView):
    model = Post
    template_name = 'post/post_delete.html'
    success_url = reverse_lazy('post:post_list')


class CommentCreateView(CreateView):
    model = Comment
    form_class = CommentForm
    template_name = 'post/post_detail.html'

    def form_valid(self, form):
        form.instance.author = self.request.user
        form.instance.post = Post.objects.get(slug=self.kwargs['slug'])
        return super().form_valid(form)

    def get_success_url(self):
        return reverse_lazy('post:post_detail', kwargs={'slug': self.object.post.slug})


class CommentUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = Comment
    form_class = CommentForm
    template_name = 'post/post_detail.html'
    login_url = reverse_lazy('user:auth_login')

    def get_object(self):
        return get_object_or_404(Commentasdasd, id=self.kwargs['pk'])

    def get_success_url(self):
        return reverse_lazy('post:post_detail', kwargs={'slug': self.object.post.slug})

    def test_func(self):
        comment = self.get_object()
        return comment.author == self.request.user


class CommentDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = Post
    login_url = reverse_lazy('user:auth_login')

    def get_object(self):
        return get_object_or_404(Comment, id=self.kwargs['pk'])

    def get_success_url(self):
        return reverse_lazy('post:post_detail', kwargs={'slug': self.object.post.slug})

    def test_func(self):
        comment = self.get_object()

        is_comment_author = self.request.user == comment.author

        is_post_author = (
            self.request.user == comment.post.author and
            not comment.author.is_admin and
            not comment.author.is_superuser
        )

        is_admin = self.request.user.is_superuser or self.request.user.groups.filter(
            name='Admins').exists()

        return is_comment_author or is_post_author or is_admin

blog/templates/post/post_create.html
{% extends 'layouts/post_layout.html' %} 

{% block title %}Post | BLOG IA{% endblock title %}

{% block content %}

<h2>Crear nuevo post</h2>
<form method="post" enctype="multipart/form-data">
  {% csrf_token %}
  <div class="flex flex-col gap-4">
    <p class="flex flex-col">{{ form.title.label_tag }} {{ form.title }}</p>
    <p class="flex flex-col">
      <label for="id_content">Contenido:</label> {{ form.content }}
    </p>
    <p>{{ form.allow_comments.label_tag }} {{ form.allow_comments }}</p>
    <p><input type="file" name="images" multiple /></p>
  </div>

  <button type="submit" class="bg-blue-500 text-white p-2 rounded-lg">
    Crear Post
  </button>
</form>

{% endblock content %}

blog/templates/post/post_delete.html
{% extends 'layouts/post_layout.html' %}

{% block title %}BORRAR Post | BLOG IA{% endblock title %}

{% block content %}
<div class="flex flex-col justify-center items-center min-h-[500px]">
  <h2>¿Estás seguro de que deseas eliminar este post?</h2>
  <div class="flex gap-2">
    <form method="post">
      {% csrf_token %}
      <button type="submit" class="bg-red-500 text-white p-2 rounded-lg">Si, eliminar</button>
    </form>
    <a href="javascript:history.back()" class="bg-blue-500 text-white p-2 rounded-lg">Cancelar</a>
  </div>
</div>
{% endblock content %}

blog/templates/post/post_detail.html
{% extends 'layouts/post_layout.html' %}

{% block title %}Post | BLOG IA{% endblock title %}

{% block content %}

{% if active_images %}
  <div class="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 gap-4">
    {% for img in active_images %}
    <a href="{{ img.image.url }}" target="_blank">
      <img 
        src="{{ img.image.url }}"
        alt="Portada del post {{ img.id }}"
        class="w-[400px] object-cover aspect-[16/9]">
    </a>
    {% endfor %}
  </div>
{% endif %}

<h3 class="text-2xl uppercase font-bold">{{ post.title }}</h3>

<p>{{ post.content }}</p>
<p>Publicado por: <strong class="font-bold">{{ post.author.username }}</strong></p>
<p>Fecha de publicación: {{ post.creation_date }}</p>
<p>Comentarios permitidos: {{ post.allow_comments|yesno:"Si,No" }}</p>
<div class="flex mt-8 gap-4">
  <a
    class="bg-blue-500 text-white p-2 rounded-lg"
    href="{% url 'post:post_update' slug=post.slug %}"
  >Editar post</a>
  <a
    class="bg-red-500 text-white p-2 rounded-lg"
    href="{% url 'post:post_delete' slug=post.slug %}"
  >Eliminar post</a>
</div>

<h4 class="mt-8 mb-4">Comentarios</h4>
{% if post.comments.count %}
  <ul>
    {% for comment in post.comments.all %}
      {% if comment.id == editing_comment_id %}
        <form method="post" action="{% url 'post:comment_update' comment.id %}" class="mb-8">
          {% csrf_token %}
          <p class="flex flex-col mt-4">{{ edit_comment_form.content.label_tag }} {{ edit_comment_form.content }}</p>
          <button type="submit" class="text-blue-500">Actualizar</button>
          <a href="{% url 'post:post_detail' post.slug %}" class="text-red-500">Cancelar</a>
        </form>
      {% elif comment.id == deleting_comment_id %}
        <form method="post" action="{% url 'post:comment_delete' comment.id %}" class="mb-8">
          {% csrf_token %}
          <p class="flex flex-col mt-4">¿Estás seguro de que desas eliminar este comentario?</p>
          <button type="submit" class="text-blue-500">Confirmar</button>
          <a href="{% url 'post:post_detail' post.slug %}" class="text-red-500">Cancelar</a>
        </form>
      {% else %}
        <li class="mb-8">
          <p>{{ comment.content }}</p>
          <small>Escrito por {{ comment.author.username }} el {{ comment.creation_date }}</small>
          
          {% if comment.author == user %}
            <a href="?edit_comment={{ comment.id }}" class="text-blue-500">Editar</a>
            <a href="?delete_comment={{ comment.id }}" class="text-red-500">Eliminar</a>
          {% elif user.is_collaborator and post.author == user and not comment.author.is_admin and not comment.author.is_superuser or user.is_admin or user.is_superuser %}
            <a href="?delete_comment={{ comment.id }}" class="text-red-500">Eliminar</a>
          {% endif %}
        </li>
      {% endif %}
    {% endfor %}
  </ul>
{% endif %}

{% if user.is_authenticated %}
  <h4>Agregar un comentario</h4>
  <form method="post" action="{% url 'post:comment_create' post.slug %}">
    {% csrf_token %}
    <p class="flex flex-col mt-4 mb-8">{{ add_comment_form.content.label_tag }} {{ add_comment_form.content }}</p>
    <button type="submit" class="bg-blue-500 text-white p-2 rounded-lg">Agregar comentario</button>
  </form>
{% else %}
  <p>
    <a href="{% url 'user:auth_login' %}?next={{ request.path }}" class="hover:text-blue-500">Inicia sesión</a>
    para agregar un comentario.
  </p>
{% endif %}

{% endblock content %}

blog/templates/post/post_list.html
{% extends 'layouts/post_layout.html' %}

{% block title %}Post | BLOG IA{% endblock title %}

{% block content %}
  <form method="get" class="flex flex-wrap sm:flex-nowrap gap-4 mb-6">
    <div class="w-full">
      {{ filter_form.search_query }}
    </div>
    <div class="w-full sm:w-[380px]">
      {{ filter_form.order_by }}
    </div>
    <button type="submit" class="w-full sm:w-[280px] bg-blue-500 text-white p-2 rounded-lg">Buscar</button>
  </form>

  <div class="grid grid-cols-1 gap-6">
    {% for post in object_list %}
      <div class="bg-gray-800 text-white rounded-2xl p-6">
        <h3 class="text-2xl uppercase font-bold">{{ post.title }}</h3>
        <p>{{ post.content }}</p>
        <p>Publicado por: <strong class="font-bold">{{ post.author.username }}</strong></p>
        <p>Fecha de publicación: {{ post.creation_date }}</p>
        <p>Comentarios permitidos: {{ post.allow_comments|yesno:"Si,No" }}</p>
        <p>Comentarios: {{ post.amount_comments }}</p>
        <div class="flex gap-2 mt-8">
          <a 
            class="bg-red-500 text-white p-2 rounded-lg" 
            href="{% url 'post:post_detail' slug=post.slug %}"
          >Ver post</a>
          <a 
            class="bg-red-500 text-white p-2 rounded-lg" 
            href="{% url 'post:post_delete' slug=post.slug %}"
          >Eliminar post</a>
        </div>
      </div>
    {% endfor %}
  </div>

  <div class="mt-4">
    {% if is_paginated %}
      <div class="flex justify-center items-center gap-2">
        {% if pagination.previous_page %}
          <a href="{{ pagination.previous_page }}" class="w-16 text-xs text-center bg-blue-500 text-white p-1 rounded-md">Anterior</a>
        {% else %}
          <span class="w-16 text-xs text-center bg-gray-500 text-white p-1 rounded-md">Anterior</span>
        {% endif %}

        <span class="w-10 text-center text-lg font-semibold">{{ page_obj.number }}</span>

        {% if pagination.next_page %}
          <a href="{{ pagination.next_page }}" class="w-16 text-xs text-center bg-blue-500 text-white p-1 rounded-md">Siguiente</a>
        {% else %}
          <span class="w-16 text-xs text-center bg-gray-500 text-white p-1 rounded-md">Siguiente</span>
        {% endif %}
      </div>
    {% endif %}
  </div>
{% endblock content %}

blog/templates/post/post_update.html
{% extends 'layouts/post_layout.html' %} 

{% block title %}Post | BLOG IA{% endblock title %}

{% block content %}

<h2>Actualizar post: {{ form.instance.title }}</h2>

<form method="post" enctype="multipart/form-data">
  {% csrf_token %}
  <div class="flex flex-col gap-4">
    <p class="flex flex-col">
      <label for="id_title">Titulo:</label> {{ form.title }}
    </p>
    <p class="flex flex-col">
      <label for="id_content">Contenido:</label> {{ form.content }}
    </p>
    <p>{{ form.allow_comments.label_tag }} {{ form.allow_comments }}</p>

    <h3>Images cargadas</h3>

    <div class="flex flex-col gap-4">
      {% for active_img in form.active_images %}
      <p>
        <img
          class="inline-flex w-[200px] aspect-[16/9] object-cover"
          src="{{ active_img.image.url }}"
          alt="Portada del post {{ active_img.id }}"
        />
        <input
          type="checkbox"
          name="keep_image_{{ active_img.id }}"
          id="keep_image_{{ active_img.id }}"
          checked
        />
        <label for="keep_image_{{ active_img.id }}">Activa</label>
      </p>

      {% endfor %}
    </div>

    <h3>Cargar nuevas images</h3>

    <p><input type="file" name="images" multiple /></p>
  </div>

  <a
    href="javascript:history.back()"
    class="bg-red-500 text-white p-2 rounded-lg"
    >Cancelar</a
  >
  <button type="submit" class="bg-blue-500 text-white p-2 rounded-lg">
    Guardar cambios
  </button>
</form>

{% endblock content %}