blog/blog/apps/post/urls.py
from django.urls import path
import apps.post.views as views

app_name = "post"

urlpatterns = [
    path('posts/', views.PostListView.as_view(), name="post_list"),
    path('posts/create/', views.PostCreateView.as_view(), name="post_create"),
    path('posts/<slug:slug>/', views.PostDetailView.as_view(), name="post_detail"),
    path('posts/<slug:slug>/update/', views.PostUpdateView.as_view(), name="post_update"),
    path('posts/<slug:slug>/delete/', views.PostDeleteView.as_view(), name="post_delete"),
    path('posts/<slug:slug>/comments/create/', views.CommentCreateView.as_view(), name="comment_create"),
    path('comments/<uuid:pk>/update/', views.CommentUpdateView.as_view(), name="comment_update"),
    path('comments/<uuid:pk>/delete/', views.CommentDeleteView.as_view(), name="comment_delete"),
]

blog/blog/apps/user/urls.py
from django.urls import path
import apps.user.views as views

app_name = "user"

urlpatterns = [
    path('users/profile/', views.UserProfileView.as_view(), name="user_profile"),
    path('auth/register/', views.RegisterView.as_view(), name="auth_register"),
    path('auth/login/', views.LoginView.as_view(), name="auth_login"),
    path('auth/logout/', views.LogoutView.as_view(), name="auth_logout"),
]

blog/blog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from blog.views import IndexView, not_found_view, internal_error_view, forbidden_view

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', IndexView.as_view(), name="home"),
    path('', include('apps.post.urls')),
    path('', include('apps.user.urls')),
]

handler404 = not_found_view
handler500 = internal_error_view
handler403 = forbidden_view

if settings.DEBUG:
    from django.conf.urls.static import static
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

blog/templates/components/ui/navbar.html
<nav>
  <ul class="flex gap-4">
    {% if user.is_authenticated %}
      <strong>{{ user.alias }}</strong>
      {% if user.is_collaborator %}
        <li><a href="{% url 'post:post_create' %}">Publicar</a></li>
      {% endif %}
    <li><a href="{% url 'user:user_profile' %}">Perfil</a></li>
    <li>
      <form
        method="post"
        action="{% url 'user:auth_logout' %}?next={{ request.path }}"
      >
        {% csrf_token %}
        <button type="submit">Cerrar sesión</button>
      </form>
    </li>
    {% else %}
      <li>
        <a href="{% url 'user:auth_login' %}?next={{ request.path }}"
          >Iniciar sesión</a
        >
      </li>
      <li><a href="{% url 'user:auth_register' %}">Registrarse</a></li>
    {% endif %}
  </ul>
</nav>